In [1]:

import pandas as pd

In [2]:

data={'Name':['Alice','Bob'],'Age':[25,30]}
df=pd.DataFrame(data)

In [3]:

lst=[['Alice',25],['Bob',30]]
df=pd.DataFrame(lst,columns=['Name','Age'])

In [4]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [7]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [8]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [9]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [11]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [12]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [13]:
df['Gender']=['F','M']
df.drop('Gender',axis=1, inplace=True)

In [14]:
df.isnull()

    Name    Age
0  False  False
1  False  False

In [15]:
df.dropna()

    Name  Age
0  Alice   25
1    Bob   30

In [16]:
df.fillna(0)

    Name  Age
0  Alice   25
1    Bob   30

In [17]:
df['Age'] = [25, 30]
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [18]:
df.groupby('Name')['Age'].mean()

Name
Alice    25.0
Bob      30.0
Name: Age, dtype: float64

In [19]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})
df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Marks': [85, 90, 78]
})
pd.merge(df1, df2, on='ID')

   ID     Name  Marks
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     78

In [20]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie']
})
df2 = pd.DataFrame({
    'Marks': [85, 90, 78]
})
df1.join(df2)

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [21]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\LENOVO\OneDrive\Desktop\aiml
['.ipynb_checkpoints', 'array.ipynb', 'array.npy', 'pandas.ipynb', 'Untitled.ipynb']

In [23]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

df.to_csv('output.csv', index=False)

In [24]:
df = pd.read_csv('output.csv')
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [25]:
df.to_csv('output.csv',index=False)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [26]:
df.sort_values('Age')

    Name  Age
0  Alice   25
1    Bob   30

In [27]:
df['Age'].apply(lambda x: x+1)

0    26
1    31
Name: Age, dtype: int64

In [28]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [29]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64